--Crear Tabla Almacén

CREATE TABLE ALMACEN (  NUMERO_ALMACEN INTEGER,
                        UBICACION_ALMACEN VARCHAR2(50),
                        CONSTRAINT PK_NUM_ALM PRIMARY KEY (NUMERO_ALMACEN));

--GENERAR PROCEDIMIENTOS ALMACENADOS NECESARIOS
--INSERTAR
CREATE OR REPLACE PROCEDURE guardar_almacen(my_num_almacen IN INTEGER,
                            my_ubicacion IN VARCHAR2)
AS
--VARIABLES LOCALES SI SE REQUIEREN
--
BEGIN
--CUERPO O LÓGICA DEL PROCEDIMIENTO
INSERT INTO ALMACEN VALUES(my_num_almacen, my_ubicacion);
END;
/

--USAREMOS UN BLOQUE PL-SQL PARA PROBAR QUE ESTÁ BIEN NUESTRO PROCEDIMIENTO
BEGIN
GUARDAR_ALMACEN(321,'ECATEPEC');
END;
/

SELECT * FROM ALMACEN

--PROBAR PROCEDIMIENTO CON NETBEANS

--ACTUALIZAR
--BORRAR


                        
                        
